# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c07294b15c04d7d04919539254a08be14d4834c9c47ba588a7a2d9d451e250abe64a5d098e83d6fcdc3f8250e715c9454ddb332a5a00eeda1425875fdff5ffa4

test:
  secret_key_base: 356da9ce17ac5088cad00a9dcb9e5f5e3515999cc5b0e3e0c1fedcc7d66331e2a28b38db6ad8b35196de09f995474c3a2cb3d98de7013062c9d0be36fdb830df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
